use iced::widget::text;
use iced::{Command, Element};

use crate::message::Message;

/// Message generated by dashboard page.
#[derive(Debug, Clone)]
pub(crate) enum DashboardMessage {}

/// The state for the settings page.
#[derive(Default)]
pub(crate) struct State {}

/// Handle theme change.
pub(crate) fn update(_: &mut State, message: DashboardMessage) -> Command<Message> {
    match message {}
}

/// Generate the view for the settings page.
pub(crate) fn view(_: &State) -> Element<'static, Message> {
    text("Dashboard").into()
}
