use iced::widget::{column, radio, text, text_input};
use iced::Element;
use serde::{Deserialize, Serialize};

use crate::message::{Message, ThemeType};
use crate::params::{GAP, GAP2};

/// Message generated by settings page.
#[derive(Debug, Clone)]
pub(crate) enum SettingsMessage {
    /// Request to change theme.
    ThemeChanged(ThemeType),
    /// Legacy API key changed.
    ThetvdbLegacyApiChanged(String),
}

/// The state for the settings page.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct State {
    #[serde(default)]
    pub(crate) theme: ThemeType,
    #[serde(default)]
    pub(crate) thetvdb_legacy_apikey: String,
}

impl Default for State {
    #[inline]
    fn default() -> Self {
        Self {
            theme: ThemeType::Dark,
            thetvdb_legacy_apikey: String::new(),
        }
    }
}

impl State {
    /// Handle theme change.
    pub(crate) fn update(&mut self, message: SettingsMessage) -> bool {
        match message {
            SettingsMessage::ThemeChanged(theme) => {
                self.theme = theme;
                false
            }
            SettingsMessage::ThetvdbLegacyApiChanged(string) => {
                self.thetvdb_legacy_apikey = string;
                true
            }
        }
    }

    /// Generate the view for the settings page.
    pub(crate) fn view(&self) -> Element<'static, Message> {
        let choose_theme = [ThemeType::Light, ThemeType::Dark].iter().fold(
            column![text("Theme:")].spacing(GAP),
            |column, theme| {
                column.push(radio(
                    format!("{:?}", theme),
                    *theme,
                    Some(self.theme),
                    |theme| Message::Settings(SettingsMessage::ThemeChanged(theme)),
                ))
            },
        );

        let thetvdb_legacy_apikey = column![
            text("TheTVDB Legacy API Key:"),
            text_input("Key...", &self.thetvdb_legacy_apikey, |value| {
                Message::Settings(SettingsMessage::ThetvdbLegacyApiChanged(value))
            }),
        ]
        .spacing(GAP);

        column![choose_theme, thetvdb_legacy_apikey]
            .spacing(GAP2)
            .padding(GAP2)
            .into()
    }
}
