name: CI

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install 1.65 --profile minimal
    - run: rustup default 1.65
    - uses: Swatinem/rust-cache@v2
    - run: cargo build

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - run: rustup default stable
    - uses: Swatinem/rust-cache@v2
    - run: cargo test

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - run: rustup default stable
    - uses: Swatinem/rust-cache@v2
    - run: cargo build
